sudo: true
language: node_js
node_js:
  - "8"
git:
  depth: 1
branches:
  only:
  - master
cache:
  timeout: 1800
  yarn: true
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  email: false
os:
- linux
- osx
before_install:
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install nsis; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install nsis; fi